[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Taras Nytiaha", email = "taras.nytiaha@gmail.com"},
]
dependencies = [
    "aiogram>=2.25.1",
]
requires-python = ">=3.11"
license = {text = "MIT"}
